blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogListView, BlogDetailView, BlogDeleteView, published_toggle

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name="blog_list"),
    path('create/', BlogCreateView.as_view(), name="blog_create"),
    path('update/<int:pk>', BlogUpdateView.as_view(), name="blog_update"),
    path('detail/<int:pk>', BlogDetailView.as_view(), name="blog_detail"),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name="blog_delete"),
    path('published/<int:pk>', published_toggle, name='published_toggle')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    date_of_create = models.DateField(auto_now=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ('date_of_create',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'image',)
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.owner = self.request.user
            new_blog.save()

            return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = '__all__'

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('slug')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


def published_toggle(request, pk):
    post_item = get_object_or_404(Blog, pk=pk)
    if post_item.is_published:
        post_item.is_published = False
    else:
        post_item.is_published = True
    post_item.save()
    return redirect(reverse('blog:blog_list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пост "{{ object.title }}" ?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{%  extends 'shop/base.html'%}
{% load extras2 %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <img class="card-img-top"
                             src="{{ object.image|mediapath }}"
                             alt="Card image cap">
                    <h3 class="card-title">Пост "{{ object.title }}" ({{ object.slug }})</h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body text-dark">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:blog_create' %}">Добавить пост</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card md-4 box-shadow">
        <div class="card-body text-dark">
            <p class="card-text">
                {{ object|title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blog:blog_detail' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Показать</a>
                    <a href="{% url 'blog:blog_update' object.pk %}"
                       type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                    <a href="{% url 'blog:blog_delete' object.pk %}"
                       type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                </div>
<!--                {% if object.is_published %}-->
<!--                <a class="btn btn-warning" href="{% url 'blog:published_toggle' object.pk %}">Снять с публикации</a>-->
<!--                {% else %}-->
<!--                <a class="btn btn-success" href="{% url 'blog:published_toggle' object.pk %}">Опубликовать</a>-->
<!--                {% endif %}-->
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}