blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogListView, BlogDetailView, BlogDeleteView, published_toggle

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name="blog_list"),
    path('create/', BlogCreateView.as_view(), name="blog_create"),
    path('update/<int:pk>', BlogUpdateView.as_view(), name="blog_update"),
    path('detail/<int:pk>', BlogDetailView.as_view(), name="blog_detail"),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name="blog_delete"),
    path('published/<int:pk>', published_toggle, name='published_toggle')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, VerifyCodeView, UserUpdateView, get_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_code/', VerifyCodeView.as_view(), name='verify_code'),
    path('get_new_password', get_new_password, name='get_new_password'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    #path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

users/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models

from shop.models import NULLABLE


class User(AbstractUser):
    username = None

    code = ''.join([str(random.randint(0, 9)) for _ in range(6)])

    email = models.EmailField(unique=True, verbose_name='email')

    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='аватар')
    phone = models.CharField(max_length=35, **NULLABLE, verbose_name='номер телефона')
    country = models.CharField(max_length=100, **NULLABLE, verbose_name='страна')

    verify_code = models.CharField(max_length=6, default=code, verbose_name='Код верификации')
    is_verified = models.BooleanField(default=False, verbose_name='Верификация')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django import forms

from shop.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'avatar', 'phone', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput() #скрыть поле пароль


class NewPasswordForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = User
        fields = ('email',)

users/views.py
import random

from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse

from django.views import View
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserProfileForm, NewPasswordForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:verify_code')
    template_name = 'users/register.html'

    def form_valid(self, form: UserRegisterForm):
        new_user = form.save()

        # verification_code = make_verification_code()
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Код подтверждения почты для доступа на сайт: {new_user.verify_code}.',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email],
        )
        return super().form_valid(form)


class VerifyCodeView(View):
    model = User
    template_name = 'users/verify_code.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request, *agrs, **kwargs):
        verify_code = request.POST.get('verify_code')
        user = User.objects.filter(verify_code=verify_code).first()
        if user:
            user.is_verified = True
            user.save()
            return redirect('users:login')
        return redirect('users:verify_code')


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserProfileForm

    def get_object(self, queryset=None): #избавляет от необходимости ввода pk, редактирует текущего юзера
        return self.request.user


# def generate_new_password(request):
#     new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
#     send_mail(
#         subject='Вы сменили пароль',
#         message=f'Ваш новый пароль: {new_password}',  # {new_user.verify_code}
#         from_email=settings.EMAIL_HOST_USER,
#         recipient_list=[request.user.email],
#     )
#     request.user.set_password(new_password)
#     request.user.save()
#     return redirect(reverse('shop:home'))


def get_new_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        # new_password = BaseAbstractUser().manager.make_random_password()
        new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        send_mail(
            subject='Пароль изменён',
            message=f'Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        user.set_password(new_password)
        user.save()
        return redirect(reverse('users:login'))
    else:
        form = NewPasswordForm
        context = {
            'form': form,
        }
        return render(request, 'users/new_password.html', context)

users/templates/users/login.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-12">
        <div class="card">
            <div class="card-header text-dark"></div>
            <div class="card-body text-dark">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-dark">LOGIN</button>
                </form>
            </div>
            <div class="card-footer text-dark"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/new_password.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="col-3"></div>
    <div class="col-6">
        <form class="form-signin" method="post">
            {% csrf_token %}
            <div class="card text-dark">
                <div class="card-header">
                    <h3 class="card-title">
                        Создать новый пароль
                    </h3>
                </div>
                <div class="card-body">
                    {{ form }}
                </div>
                <button type="submit" class="btn btn-dark">Отправить пароль</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-12">
        <div class="card">
            <div class="card-header text-dark"></div>
            <div class="card-body text-dark">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-dark">REGISTRATION</button>
                </form>
            </div>
            <div class="card-footer text-dark"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-12">
        <div class="card">
            <div class="card-header text-dark">
                Мой профиль
            </div>
            <div class="card-body text-dark">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-dark">SAVE</button>
                </form>
            </div>
            <div class="card-footer text-dark">
                <a href="{% url 'users:get_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/verify_code.html
{% extends 'shop/base.html' %}

{%block content%}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header text-dark">
                    <h3 class="card-title">
                        Введите код подтверждения
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="text" name="verify_code" class="form-control" id="name" placeholder="Введите код" required>
                    <button type="submit" class="btn btn-primary">Подтвердить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}