blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogListView, BlogDetailView, BlogDeleteView, published_toggle

app_name = BlogConfig.name


urlpatterns = [
    path('', BlogListView.as_view(), name="blog_list"),
    path('create/', BlogCreateView.as_view(), name="blog_create"),
    path('update/<int:pk>', BlogUpdateView.as_view(), name="blog_update"),
    path('detail/<int:pk>', BlogDetailView.as_view(), name="blog_detail"),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name="blog_delete"),
    path('published/<int:pk>', published_toggle, name='published_toggle')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from shop.apps import ShopConfig
from shop.views import home, contacts, CategoryListView, ProductListView, ProductDetailView, ProductCreateView, \
    ProductUpdateView, ProductAllListView, published_toggle

app_name = ShopConfig.name


urlpatterns = [
    path('', home, name="home"),
    path('home/', home, name="home"),
    path('contacts/', contacts, name="contacts"),
    path('catalog/', CategoryListView.as_view(), name="catalog"),
    path('products_category/<int:pk>', ProductListView.as_view(), name="products_category"),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name="product"),
    path('all_products/', ProductAllListView.as_view(), name="all_products_list"),
    path('product/create/', ProductCreateView.as_view(), name="product_create"),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name="product_update"),
    path('published/<int:pk>', published_toggle, name='published_toggle')
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, VerifyCodeView, UserUpdateView, get_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_code/', VerifyCodeView.as_view(), name='verify_code'),
    path('get_new_password', get_new_password, name='get_new_password'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    #path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

shop/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='category/', verbose_name='Изображение', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='product/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price_for_one = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена за штуку')
    date_of_create = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    date_of_last_change = models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)

    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name} ({self.category}) - {self.price_for_one}'

    @property
    def current_version(self):
        return Version.objects.filter(is_current=True, product_id=self.id).first()

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('category', 'name',)

        permissions = [
            (
                'set_published',
                'Can publish products',
            )
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.FloatField(verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Название версии')
    is_current = models.BooleanField(default=False, verbose_name='Текущая версия')

    def __str__(self):
        return f'Версия {self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

shop/forms.py
from django import forms

from shop.models import Product, Version


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_name = self.cleaned_data['name'].lower().strip()
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа',
                           'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in forbidden_words:
            if word in cleaned_name:
                raise forms.ValidationError(f'В названии продукта не должно быть слова: {word}')
        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data['description'].lower().strip()
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа',
                           'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in forbidden_words:
            if word in cleaned_description:
                raise forms.ValidationError(f'В описании продукта не должно быть слова: {word}')
        return cleaned_description


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

shop/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from pytils.translit import slugify

from shop.forms import ProductForm, VersionForm
from shop.models import Category, Product, Version
from shop.services import get_cached_categories_of_products


def home(request):
    return render(request, 'shop/home.html')


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_cached_categories_of_products()
        context_data['title'] = 'Категории товаров'
        return context_data


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')
    return render(request, 'shop/contacts.html')


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    extra_context = {
        'title': 'Информация о товаре',
    }


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('shop:home')

    def form_valid(self, form):
        if form.is_valid():
            new_product = form.save()
            new_product.slug = slugify(new_product.name)
            new_product.owner = self.request.user
            new_product.save()

            return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    #permission_required = 'shop.change_product'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_success_url(self, *args, **kwargs):
        return reverse('shop:home', args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    # def test_func(self):
    #     if self.request.user == self.product.owner:
    #         content_type = ContentType.objects.get_for_model(Product)
    #         permissions = Permission.objects.get(
    #             codename="change_product",
    #             content_type=content_type,
    #         )
    #         self.user.user_permissions.add(permissions)


class ProductAllListView(ListView):
    model = Product
    form_class = ProductForm
    template_name = 'shop/all_products_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(is_published=True)
        return queryset


@login_required
@permission_required('shop.set_published')
def published_toggle(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    if product_item.is_published:
        product_item.is_published = False
    else:
        product_item.is_published = True
    product_item.save()
    return redirect(reverse('shop:home'))

shop/templates/shop/all_products_list.html
{% extends 'shop/base.html' %}
{% load extras1 %}

{% block content %}
<div class="row py-xl-5">
    <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Free Market</h1>
        <p class="lead text-muted">Раздел обмена товарами между пользователями</p>
        <p>
            {% if user.is_authenticated %}
            <a href="{% url 'shop:product_create' %}" class="btn btn-secondary my-2">Создать объявление</a>
            {% else %}
            <a href="{% url 'users:login' %}" class="btn btn-primary my-2">Для создания объявления необходимо авторизоваться</a>
            {% endif %}
        </p>
    </div>
</div>
<div class="album bg-dark">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-title text-dark">{{ object.name }}</div>
                    <img src="{{ object.image|mediapath  }}"/>

                    <div class="card-body">
                        <p class="card-text text-dark">{{ object.description }}</p>
                        <p class="card-text text-dark">{{ object.price_for_one }} руб.</p>
                        {% if object.current_version %}
                        <p class="card-text text-dark">{{ object.current_version }}</p>
                        {% endif %}
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'shop:product' object.pk %}"
                                   class="btn btn-sm btn-outline-secondary">Перейти
                                    к товару</a>
                                {% if user == object.owner or user.is_staff %}
                                <a href="{% url 'shop:product_update' object.pk %}"
                                   class="btn btn-sm btn-outline-secondary">Изменить товар</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/base.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SHOP</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-white bg-dark">
<div class="cover-container d-flex p-3 mx-auto flex-column">
    {% include 'shop/includes/inc_menu.html' %}
    {% block content %}
    {% endblock %}
    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>

</body>
</html>

shop/templates/shop/catalog.html
{% extends 'shop/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ title }}</h1>
    </div>
</section>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-6">
        {% include 'shop/includes/inc_cat.html' %}
        <div class="d-flex justify-content-between align-items-center">
            <p class="lead">
                <a href="{% url 'shop:products_category' object.pk %}"
                   class="btn btn-lg btn-secondary fw-bold border-dark bg-white">Перейти
                    в категорию</a>
            </p>
        </div>
    </div>
</div>
</div>
{% endfor %}
</div>
{% endblock %}

shop/templates/shop/category_list.html
{% extends 'shop/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ title }}</h1>
    </div>
</section>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-6">
        {% include 'shop/includes/inc_cat.html' %}
        <div class="d-flex justify-content-between align-items-center">
            <p class="lead">
                <a href="{% url 'shop:products_category' object.pk %}"
                   class="btn btn-lg btn-secondary fw-bold border-dark bg-white">Перейти
                    в категорию</a>
            </p>
        </div>
    </div>
</div>
</div>
{% endfor %}
</div>
{% endblock %}

shop/templates/shop/contacts.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <div class="mb-3">
                            <input type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/home.html
{% extends 'shop/base.html' %}

{% block content %}
<main class="px-3">
    <h1>Мой заголовок</h1>
    <p class="lead">Тут будет текст.</p>
</main>
{% endblock %}

shop/templates/shop/product.html
{% extends 'shop/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ title }}</h1>
    </div>
</section>
<div class="row">
    {% for object in object_list %}
    <div class="card mb-4 box-shadow">
        {% include 'shop/includes/inc_cat.html' %}
                <h4 class="card-title text-dark">{{ object.price_for_one }} руб.</h4>
            </div>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <button type="button" class="btn btn-dark btn-lg px-4 gap-3">Заказать в один клик</button>
                <button type="button" class="btn btn-dark btn-lg px-4">Добавить в корзину</button>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ title }}</h1>
    </div>
</section>
<div class="row">
    <div class="card mb-4 box-shadow">
        {% include 'shop/includes/inc_cat.html' %}
                <h4 class="card-title text-dark">{{ object.price_for_one }} руб.</h4>
            </div>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <button type="button" class="btn btn-dark btn-lg px-4 gap-3">Заказать</button>
                <button type="button" class="btn btn-dark btn-lg px-4">
                    Задать вопрос владельцу {{ object.owner }}</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/product_form(Nikita).html
{% extends 'shop/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">

                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>

                        </div>
                    </div>
                </div>
                {% if formset %}
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Версии товара</h3>
                            </div>
                            <div class="card-body">
                                {{ formset.management_form }}
                                {% for form in formset.forms %}
                                    {{ form.as_p }}
                                    {% if not forloop.last %}
                                        <hr class="mb-4">
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

shop/templates/shop/product_form(my).html
{% extends 'shop/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body text-dark">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{formset.management_form}}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/product_form.html
{% extends 'shop/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body text-dark">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
                <div class="card-footer">
                    {% if object %}
                        {% if perms.shop.set_published %}
                            {% if object.is_published %}
                                <a class="btn btn-outline-warning" href="{% url 'shop:published_toggle' object.pk %}">Снять с
                        публикации</a>
                            {% else %}
                                <a class="btn btn-outline-success" href="{% url 'shop:published_toggle' object.pk %}">Опубликовать</a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% if formset %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title text-dark">Версии товара</h3>
                </div>
                <div class="card-body text-dark">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr class="mb-4">
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</form>
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ title }}</h1>
    </div>
</section>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-6">
        {% include 'shop/includes/inc_cat.html' %}
        <div class="d-flex justify-content-between align-items-center">
            <p class="lead">
                {% if object.is_published %}
                <a href="{% url 'shop:product' object.pk %}"
                   class="btn btn-lg btn-secondary fw-bold border-dark bg-white">Перейти
                    к товару</a>
                {% endif %}
            </p>
        </div>
    </div>
</div>
</div>
{% endfor %}
</div>
{% endblock %}

shop/templates/shop/products_category.html
{% extends 'shop/base.html' %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ title }}</h1>
    </div>
</section>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-6">
        {% include 'shop/includes/inc_cat.html' %}
        <div class="d-flex justify-content-between align-items-center">
            <p class="lead">
                <a href="{% url 'shop:product' object.pk %}"
                   class="btn btn-lg btn-secondary fw-bold border-dark bg-white">Перейти
                    к товару</a>
            </p>
        </div>
    </div>
</div>
</div>
{% endfor %}
</div>
{% endblock %}